# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U_hIrS6DYCqE19Y3FawlTz7Qnh3VuaaZ

JOGO DA FORCA EM PYTHON
"""

# Importar o módulo random para escolher uma palavra aleatória
import random

# Definir uma lista de palavras possíveis
palavras = ["amarelo", "roxo", "vermelho", "azul", "rosa"]

# Escolher uma palavra da lista
palavra = random.choice(palavras)

# Inicializar as variáveis
acertos = []
 # Lista de letras acertadas
erros = 0
 # Número de erros
max_erros = 6
# Número máximo de erros permitidos
ganhou = False
# Variável para indicar se o jogador ganhou ou não

# Mostrar o desenho da forca
def desenho(erros):
  print("  +---+")
  print("  |   |")

  if erros == 0:
    print("      |")
    print("      |")
    print("      |")
    print("      |")
  elif erros == 1:
    print("  O   |")
    print("      |")
    print("      |")
    print("      |")
  elif erros == 2:
    print("  O   |")
    print("  |   |")
    print("      |")
    print("      |")
  elif erros == 3:
    print("  O   |")
    print(" /|   |")
    print("      |")
    print("      |")
  elif erros == 4:
    print("  O   |")
    print(" /|\  |")
    print("      |")
    print("      |")
  elif erros == 5:
    print("  O   |")
    print(" /|\  |")
    print(" /    |")
    print("      |")
  else:
    print("  O   |")
    print(" /|\  |")
    print(" / \  |")
    print("      |")

  print("=========\n")

# Mostrar a palavra oculta com os acertos e os espaços
def mostrar_palavra():
  for letra in palavra:
    if letra in acertos:
      print(letra, end=" ")
    else:
      print("_", end=" ")
  print()

# Loop principal do jogo
while True:
  # Mostrar o desenho da forca e a palavra oculta
  desenho(erros)
  mostrar_palavra()

  # Verificar se o jogador ganhou ou perdeu
  if erros == max_erros:
    print("Você perdeu!")
    print(f"A palavra era: {palavra}")
    break
  if "_" not in palavra:
    print("Você ganhou!")
    ganhou = True
    break

  # Pedir uma letra ao jogador
  letra = input("Digite uma letra: ").lower()

  # Verificar se a letra é válida
  if len(letra) != 1 or not letra.isalpha():
    print("Letra inválida!")
    continue

  # Verificar se a letra já foi digitada
  if letra in acertos:
    print("Você já digitou essa letra!")
    continue

  # Verificar se a letra está na palavra
  if letra in palavra:
    print("Você acertou uma letra!")
    acertos.append(letra)
  else:
    print("Você errou uma letra!")
    erros += 1